### ISSUE TITLE
Add teacher-only tests

### ISSUE THREAD

**Issue by ninewise** [dodona-edu/judge-java#48]
As was requested by mail. Conversations (in Dutch) below.

> **Frederik Gailly to Felix Van der Jeugt**
> Is het mogelijk om testen toe te voegen die enkel zichtbaar zijn
> voor de lesgever. Ik meen me te herinneren dat dit ging maar ik vind
> hiervoor nergens info over hoe je dit moet doen.

> **Felix Van der Jeugt to Frederik Gailly**
> Dit zit in Dodona maar ik denk dat buiten de Haskell-judge niemand
> daar gebruik van maakt. Zelf hou ik liefst alle testen zichtbaar voor
> de studenten en voeg ik eventueel na de evaluatie nog testen toe (op
> Dodona of enkel lokaal).

> **Frederik Gailly to Dodona Team**
> Ik zou nu bijkomende testen aan mijn oefeningen willen toevoegen die
> me ondersteunen bij de evaluatie. Zijn de resultaten van deze testen
> zichtbaar voor de studenten ? Ik zal deze later wel publiceren maar
> ik wil dit pas doen bij het bekend maken van de punten en voor alle
> studenten op het zelfde moment. Ik vermoed een beetje dat studenten
> nu via hun profiel ook hun submissions kunnen bekijken en dus ook de
> testen kunnen zien.
>
> Een oplossing zou zijn bij de testen een tabblad dat niet zichtbaar is
> voor de studenten. Ik dacht dat dit er al ergens eens had gezien maar
> volgens mij lukt dit niet bij de java judge.

> **Peter Dawyndt to Frederik Gailly**
> Dodona ondersteunt inderdaad verborgen tabs (onzichtbaar voor
> studenten, zichtbaar voor lesgevers). Vraag is hier of die ook
> door de Java-judge ondersteund worden, en indien ja, of de testen
> in de verborgen tab ook in rekening gebracht worden bij de globale
> beoordeling van de ingediende oplossing. Vandaar dat ik Felix ook mee
> in CC zet.

> **Frederik Gailly to Dodona Team**
> Ik had Felix reeds gecontacteerd in verband met niet zichtbaar tabblad
> en de Java judge ondersteunt dit niet. Is het eventueel mogelijk om
> dit op korte termijn Felix te helpen met dit te implementeren. Zou
> voor mij wel echt handig zijn. Ik zie niet goed hoe ik dit nu anders
> kan oplossen.

Summary: Frederik Gailly would like to have tabs only visible to
teachers, so he could have the results on additional tests while
grading, without showing this to the students.

Open questions:

* Should these tests influence the status of the submission?

* Do we add some message to the teacher to notify it's a tab visible
  only to them? I don't think Dodona adds such message for us
  (@bmesuere?).

**Comment by fgailly** [comment]
Open Question 1: The status of the submission should only be determined by the tests of the visible tab. When a teacher wants to make the test available to student the tab should be made visible and the teacher can afterwards reevaluate the tests. This will also change the status of the submission

Open question 2: The teacher should see which tabs are available to students and which are not

**Comment by bmesuere** [comment]
Right now, there is nothing to indicate that a tab is hidden for students

**Comment by fgailly** [comment]
> Right now, there is nothing to indicate that a tab is hidden for students

but you can indicate in the label of the tab?

**Comment by ninewise** [comment]
I'll create an issue on Dodona to indicate the permission of the tab. For now, a manual marker in the TabTitle (or just remember it) should do.

**Comment by ninewise** [comment]
Having the judge ignore the status of failing contexts in a staff-only tab is a bit hard. Dodona automatically determines the status of a submission by checking the statusses of the contexts. If any context is unaccepted, so is the submission.

1. Either Dodona should be changed [on this line](https://github.com/dodona-edu/dodona/blob/develop/app/runners/result_constructor.rb#L160) to ignore failed contexts in a staff-only tab.
2. The judge should [set all contexts to accepted](https://github.com/dodona-edu/judge-java12/blob/master/src/dodona/junit/JSONListener.java#L135) in a staff-only tab. (But this would have Dodona draw green vertical lines next to failed tests, making them harder to see. The red crosses would remain red.)

**Comment by ninewise** [comment]
I've discussed this with the Dodona team and the second solution probably won't do. The diffing between the expected and generated output would not be shown as well, so the feedback table would be practically useless for the teacher.

@fgailly would it be possible to work with visible (failed) statusses for your additional (hidden) tests or with just visible tests? If not, could you request above solution (1) as an issue on the Dodona repository? Deploying this might take some more time than changes to the judge, though.

**Comment by fgailly** [comment]
Maybe strange idea but is it possible to switch to an evaluation mode for an assignment. This would mean that the status of the submission freezes for students (i.e. submission is evaluated). The teacher can add tests as part of his evaluation but the new status is only visible for the student when the evaluation mode for the assignment is switched off.

**Comment by ninewise** [comment]
This sounds like a possible solution, too, but it would require changes on Dodona as well - the judge couldn't do this.

**Comment by fgailly** [comment]
> would it be possible to work with visible (failed) statusses for your additional (hidden) tests or with just visible tests? 

I do not completely understand your solution. Does this mean that changing this line in Dodona, results in making sure that tests is the hidden tab don't influence the status of the submission (which is seen by the student).

**Comment by ninewise** [comment]
No, as I understand, these are the options:

1. Leaving it as is. You just add visible tests, rejudge on Dodona and the students get to see the additional tests fail.
2. Using the PR #49 I wrote this afternoon. This allows hiding the tests, but the students will see their status change.
3. Applying earlier (2) on top of PR #49. This allow hiding the tests *and* the status, but the teacher wouldn't be able to see how a test failed in the judge either (since it wouldn't actually fail), only that it failed.
4. Earlier (1): Creating an issue on the Dodona repository asking to discard test results in hidden tabs.

**Comment by fgailly** [comment]
I propose this:

- we start with solution 2 which needs no changes at the  Dodona side. I will inform my students that the status will change but that this is because I am evaluating their solution.
- I will create two issues on the Dodona repository: 1) asking to discard test results in the hidden tab and 2) the idea of putting a submission in evaluation mode.

Do you agree? Do you have time to implement solution 2 ? In case you have other priorities, I need to decide if solution 1 is good enough right now.

**Comment by ninewise** [comment]
I agree. I've already implemented PR 49 so I'll merge that after review (probably tomorrow morning).

**Comment by ninewise** [comment]
@fgailly The changes have been deployed to the judge. You can now add `@TabPermission(Permission.STAFF)` to a test class (with imports `dodona.junit.TabPermission` and `dodona.feedback.Permission`) as shown [here](https://github.com/dodona-edu/judge-java12/blob/master/integration-tests/tab-permission/evaluation/TabPermissionTest.java#L7). This will hide the tab from the students but will have no effect otherwise.
